---
- hosts: all
  become: true
  tasks:
   - name: install java
     become: yes
     apt:
       name: openjdk-8-jdk
       state: present
   - name: install maven
     apt:
       name: maven
       state: present
       update_cache: yes
     notify:
     - run update
   - name: install nginx
     apt:
       name: nginx
       state: latest
   - name: install docker
     apt:
       pkg: docker.io
       state: present
   - name: start docker service
     service:
        name: docker
        state: started
        enabled: true
   - name: deploy batch10 image
     command: sudo docker run -it -d -p 8888:8888 prabhat2020/case:1.0.0
